# L00 - Python alapok
## Hasznos Python alap ismeretek


Ebben a gyakorlatban bemutatunk néhány Pythonban a tárgy során használt elemet, mit hasznosnak tartunk a teljesség igénye nélkül.

A Phyton erősen típus orientált, dinamikusan tipusdefiniált (nem kell a változókat declarálni, hozzá rendeli magától), case sensitive (var és VAR két különböző változó) és objektum orientált programnyelv (minden egy objectum).

Egy változót létrehozva a megfelelő típusú objektum jön létre.

### 1. Help 

Segítséghez használhatjuka help() függvényt, vagy a dir() függvényt, ami az objektumra alkalmazható függvnyeket listáza ki.

In [1]:
a = -5

In [2]:
help(a)

Help on int object:

class int(object)
 |  int([x]) -> integer
 |  int(x, base=10) -> integer
 |  
 |  Convert a number or string to an integer, or return 0 if no arguments
 |  are given.  If x is a number, return x.__int__().  For floating point
 |  numbers, this truncates towards zero.
 |  
 |  If x is not a number or if base is given, then x must be a string,
 |  bytes, or bytearray instance representing an integer literal in the
 |  given base.  The literal can be preceded by '+' or '-' and be surrounded
 |  by whitespace.  The base defaults to 10.  Valid bases are 0 and 2-36.
 |  Base 0 means to interpret the base from the string as an integer literal.
 |  >>> int('0b100', base=0)
 |  4
 |  
 |  Methods defined here:
 |  
 |  __abs__(self, /)
 |      abs(self)
 |  
 |  __add__(self, value, /)
 |      Return self+value.
 |  
 |  __and__(self, value, /)
 |      Return self&value.
 |  
 |  __bool__(self, /)
 |      self != 0
 |  
 |  __ceil__(...)
 |      Ceiling of an Integral retur

In [3]:
dir(a)

['__abs__',
 '__add__',
 '__and__',
 '__bool__',
 '__ceil__',
 '__class__',
 '__delattr__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floor__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getnewargs__',
 '__gt__',
 '__hash__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__le__',
 '__lshift__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rlshift__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rrshift__',
 '__rshift__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__trunc__',
 '__xor__',
 'bit_length',
 'conjugate',
 'denominator',
 'from_bytes',
 'imag',
 'numerator',
 'real',
 'to_bytes']

A __doc__ függvény meghívásával egy kiválasztott method dukumentációs stringjét hívhatjuk elő.

In [4]:
abs.__doc__

'Return the absolute value of the argument.'

In [5]:
abs(a)

5

### 2. Syntax

A Phython nem használ blokk elválasztó karaktert, mindent behúzásokkal tagol. Minden block első sora, ami behúzást vár, :-ra végződik.
Egy soros komment a # karakter használatával lehetséges, több soros komment a """ """ köz írva. Értéket a = operátorral adunk meg, amellyel tulajdon képpen nevet rendelünk az objektumhoz. Egyenlőség teszt a == operátorral lehetséges. Incrementálni és decrementálni a += és -= operátorokkal lehetséges. Ez többéle adattípuson is működik. 

In [6]:
myvar = 3
myvar += 2
myvar

5

In [7]:
myvar -= 1
myvar

4

In [8]:
"""Ez egy többsoros komment
A következő sorok két stringet adnak össze."""
mystring = "Hello"
mystring += " world."
print(mystring)

Hello world.


In [9]:
# A következő kód egy sorban(!) cseréli ki két változó értékét.
# Ez nem sérti meg az erős típusdefiniáltságot, mivel nem értéket 
# rendelünk hozzá, hanem új objektumokat rendelünk a régi nevekhez. 
myvar, mystring = mystring, myvar

In [10]:
myvar

'Hello world.'

In [11]:
mystring

4

### 3. Adattípusok

A Pythonban elérhető adattípusok a listák (list), tupleök (tuple) és szótárak (dictionariy). 
- A listák gyakorlatilag egydimenziós vektorok (de listák lehetnek lista elemek is).<br>
- A szótárak (dictionary) kulcsszó érték párokat tartalmaznak. <br>
- A tuples olyan Python objektumok listája, mely nem változtatható a deklarációját követően. A hagyományos listától annyiban különbözik, hogy ennek elemeit nem módosíthatjuk, de a többi listaműveletet végre lehet velük hajtani.

Phyton tömbök tartalmazhatnak bármilyen adattípust, így egyazon tömb tartalmazhat akár integert, stringet, listát, dictionary-t stb. <br>
Az indexelés minden tömb típusnál 0-tól indul. Negítív számokkal hátulról címezhetünk meg elemet, így a -1 az utolsó elemet jelöli.

In [12]:
sample = [1, ["another", "list"], ("a", "tuple")]
# ennek a listának első eleme egy integer, második eleme egy két elemű lista, harmadik eleme pedig egy 2 elemű tuple.

In [13]:
mylist = ["List item 1", 2, 3.14]
# a mylist egy olyan lista mely tartalmaz strig, integer és float értéket is

In [14]:
# lista első (azaz 0.) elemének kiíratása
mylist[0]

'List item 1'

In [15]:
# Listaelem megváltoztatása
mylist[0] = "List item 1 again"

In [16]:
mylist[0]

'List item 1 again'

In [17]:
# Lista utolsó eleme
mylist[-1]

3.14

In [18]:
mydict = {"Key 1": "Value 1", 2: 3, "pi": 3.14}

In [19]:
mydict["pi"]

3.14

In [20]:
# Szótár "pi" nevű elemének értékének megváltoztatása
mydict["pi"] = 3.15

In [21]:
# Tuple létrehozása
mytuple = (1, 2, 3)

In [22]:
# Tuple hosszának kiíratása
len(mytuple) 

3

In [23]:
# Új hosszfüggvny megadása
myfunction = len

In [24]:
print(myfunction(mylist))

3


In [25]:
print(mylist)

['List item 1 again', 2, 3.14]


Tömb bizonyos elemeihez való hozzáféréshez egy intervallumot is megadhatuk a : karakterrel elválasztva. Üresen hagyva a kezdő sorszámot automatikusan a tömb legelejéről indul a számozás. Az intervallum végét üresen hagyva pedig automatikusan az utolsó elemig nézzük a tömböt.

In [26]:
print(mylist[:])

['List item 1 again', 2, 3.14]


In [27]:
print(mylist[:])

['List item 1 again', 2, 3.14]


In [28]:
print(mylist[0:2])

['List item 1 again', 2]


In [29]:
print(mylist[-3:-1])

['List item 1 again', 2]


In [30]:
print(mylist[1:])

[2, 3.14]


Az intervallumot kiegészíthetjük egy harmadik elmmel is, a lépésközzel. Ezzel a paraméterrel kiírathatjuk mondjuk minden másodiket elemet.

In [31]:
print(mylist[::2])

['List item 1 again', 3.14]


### 4. Stringek

Stringek kiíratásakor használhatunk ' vagy " idézőjelet. A két különbőző idézőjel egymásba is ágyazható kiíratáskor. 

In [32]:
print("He said 'Hello'")

He said 'Hello'


In [33]:
print('He also said "How are you?"')

He also said "How are you?"


Stringek kitöltéséhez használjuk a % operátort és egy tuple-t. Minden %s egy tuple elemmel lesz helyettesítve balról jobbra haladva. Dictionary megfogalmazás szintén használható. 

In [34]:
# Vigyázat: Figyeljünk az s végződésre "%(key)s".
print("This %(verb)s a %(noun)s." % {"noun": "test", "verb": "is"})

This is a test.


In [35]:
# Adaptálódó kiiratása
name = "Groot"
print("Hello, {}!".format(name))

Hello, Groot!


In [36]:
print(f"I am {name}!")

I am Groot!


### 5. Ciklusok, elágazások

Használható kifejezések az if, for és while. Pythonban nincs switch. Iterációk során használhatjuk még a range(<szám>) kifejezést.

In [37]:
print(range(10)) # magában kiíratva nem tűnik hasznosnak, de...

range(0, 10)


In [38]:
rangelist = list(range(10))
print(rangelist)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [39]:
for number in range(10):
    # Ellenőrizzük, hogy az aktuális szám
    # része-e a tuplenek.
    if number in (3, 4, 7, 9):
        # A 'Break' parancs kilép a for ciklusból
        # mielőtt végrehajtaná az else ágat
        print(number)
        break
    else:
        # A "Continue" a következő iterációt kezdeni. 
        # a loopban. Elég haszontalan itt, mivel
        # ez az utolsó utasítás.
        continue
else:
    # Az else ág csak opcionális, mivel csak akkor
    # fut le, ha a loop nem break-el.
    pass # Nem csinál semmit.

3


In [40]:
if rangelist[1] == 2:
    print("The second item (lists are 0-based) is 2")
elif rangelist[1] == 3:
    print("The second item (lists are 0-based) is 3")
else:
    print("Dunno")

Dunno


Ha sikerülne egy végtelen loopba kergetni a programot a Jupyter Notebook menüsávján az "interrupt kernel" gombra kattintva tudjuk csak megállítani a program futását.
A kipróbálásához először aktiváljuk a következő cella kommentjét.

In [41]:
#while rangelist[1] == 1:
#    print("We are trapped in an infinite loop!")

### 6. Függvények

Függvényeket a def kulcsszóval deklarálunk. A deklarációban adhatjuk meg az argumentumokat is, ahol alap értékeket is beállíthatunk az egyes szükséges változóknak. A föggvények visszatérési értéke lehet egy tuple, így könnyedén vissza lehet adni több változót is. <br>
A lambda függvény egy ad hoc függvény, ami egy utasítást tömörít. A paramétere referenciaként adható meg, nem modosítható tipusban (tuple, int, string). Nem módosítható a hívóban. Ennek magyarázata, hogy csak a memória helyének címét adjuk át és ha egy sorban egy új objektumot is hozzárendelnénk a régi értéket eldobnánk. 

In [42]:
# Ugyan az mint a def funcvar(x): return x + 1
funcvar = lambda x: x + 1
print(funcvar(1))

2


In [43]:
# Az an_int és a_string megadása opcionális, mivel rendelkeznek default értékkel,
# ha valamelyiket nem adnánk meg a fügvénynek meghíváskor.
def passing_example(a_list, an_int=2, a_string="A default string"):
    a_list.append("A new item")
    an_int = 4
    return a_list, an_int, a_string

In [44]:
my_list = [1, 2, 3]
my_int = 10
print(passing_example(my_list, my_int))

([1, 2, 3, 'A new item'], 4, 'A default string')


In [45]:
my_list

[1, 2, 3, 'A new item']

In [46]:
my_int

10

### 7. Kivétel kezelés

A kivételek kezelése a Pythonban a try-except blokkal lehetséges.

In [73]:
def some_function():
    try:
        # Nullával osztás hibát dob
        10 / 0
    except ZeroDivisionError:
        print("Oops, invalid.")
    else:
        # Nincs hiba, eddig jók vagyunk.
        pass
    finally:
        # Ez a code block után fut le, miután az az összes
        # hibát lekezelte. Még akkor is, ha a hibakezelés
        # közbe új hiba lép fel.
        print("We're done with that.")

In [74]:
some_function()

Oops, invalid.
We're done with that.


### 9. Importing

Külső könyvtárak használata a könyvtár beinportálása után lehetséges. Importálhatunk egész könyvtárat <br>
import [könyvtár]  <br>
, vagy könyvtárak egyes részeit, függvényeit. <br>
from [könyvtár] import [függvény] <br>
Az as paranccsal egy rövidebb kifejezést is társíthatunk a gyakran használt csomagok mellé. <br>
import [könyvtár] as [kulcsszó]

In [75]:
import random
from time import clock

randomint = random.randint(1, 100)
print(randomint)

66


### 10. File I/O

Python has a wide array of libraries built in. As an example, here is how serializing (converting data structures to strings using the pickle library) with file I/O is used:

In [90]:
# Fálj megnyitása írásra (w). Az open utáni r betű a fájlnév speciális 
# karakterek okozta kilépést hivatott megelőzni.
myfile = open(r".\Test.txt", "w")
myfile.write("This is a sample string")
myfile.close()

In [89]:
# Kiolvassuk mi van a fájlba.
myfile = open(r".\Test.txt")
print(myfile.read())
myfile.close()

This is a sample string


### 11. Globális változók kezelése 

A globális változók deklarálása a függvényen kívül történik és további definiálás nélkül használható a függvényen belül. Ha módosítani szeretnénk a függvényen belül (nem csak olvasni), akkor a fügvényen belül kell deklarálni a global kulcsszó használatával különben a Python egy új lokális változót fog létrehozni azzal a névvel.

In [91]:
number = 5

def myfunc():
    # This will print 5.
    print(number)

def anotherfunc():
    # This raises an exception because the variable has not
    # been bound before printing. Python knows that it an
    # object will be bound to it later and creates a new, local
    # object instead of accessing the global one.
    print(number)
    number = 3

def yetanotherfunc():
    global number
    # This will correctly change the global.
    number = 3

In [92]:
myfunc()

5


In [93]:
anotherfunc()
# A hibaüzenet itt elvárt.

UnboundLocalError: local variable 'number' referenced before assignment

In [94]:
yetanotherfunc()
print(number)

3


### 12 NumPy csomag:

A gyakorlatok során leggyakrabban használt csomag a NymPy lesz. Importáljuk be a NumPy -t! Az importot követően az <font color='green'>$as$</font> parancsal megadható egy rövidebb forma az egyszerűbb használatért.

In [95]:
import numpy as np

Hozzuk létre az alábbi tömböket: 

A = 
\begin{array}{ccc}
0 & 0 & 0
\end{array}

B = 
\begin{array}{c}
1\\
1\\
1
\end{array}

C = 
\begin{array}{cc}
1 & 2\\
3 & 4\\
5 & 6
\end{array}

A szintaktika: a tömb sorainak elemeit [] között vesszővel elválasztva adhatjuk meg az egyes tagokat. Több dimenziós tömbök esetén a sorokat szintén , karakterrel választhatjuk el és a sorokat egy újabb [] párosba helyezzük.

In [96]:
A = np.array([0,0,0,])
B = np.array([[1],[1],[1]])
C = np.array([[1,2],[3,4],[5,6]])
D = np.array([[0,1,2,3,4,5,6],[7,8,9,10,11,12,13],[14,15,16,17,18,19,20],[21,22,23,24,25,26,27]])
print('A:\n',A)
print('B:\n',B)
print('C:\n',C)
print('D:\n',D)

A:
 [0 0 0]
B:
 [[1]
 [1]
 [1]]
C:
 [[1 2]
 [3 4]
 [5 6]]
D:
 [[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]]


Visszaellenőrzés során a tömb dimenzióinak lekérdezése numpy.array().shape paranccsal történik.\
Feladat:
- Írassuk ki az előző cellában létrehozott mátrixok alakját!
- Írassuk ki az C mátrix első dimenziájának nagyságát!

In [97]:
print(A.shape)
print(B.shape)
print(C.shape)
print(D.shape)
print(C.shape[0])

(3,)
(3, 1)
(3, 2)
(4, 7)
3


Érdemes megfigyelni, hogy a sorvektorok esetén 1 dimenziót jelez ki a függvény, míg oszlopvektorok esetén 2 dimenziót. 

Sokszor szükségünk lehet egy adott lista, tömb vagy mátrix elemeinek számára. Ilyenkor a [numpy.ndarray.size](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.size.html "dokumentáció") -t használjuk. FONTOS, hogy ez nem azonos a shape-el, hanem a shape elemeinek szorzatával, azaz az összes elemmel.

Feladat:
- Határozzuk meg a A és D mátrixok nagyságát!

In [100]:
print(A.size)
print(D.size)

3
28


Tömb elemére történő hivatkozás az elem sor és oszlop indexével történhet. Az indexelés 0-tól kezdődik.\
Szintaktika:

<tömbnév>[sor, oszlop]

,ahol az elemek helyére :-t írva az egész sor vagy oszlop behivatkozható, illetve x:y formában határ értékekkel használva megadott részleteket emelhetünk ki a matrixból.

In [101]:
print("Egy elem")
print(C[0,0])
print("Egy sor")
print(C[0,:])
print("Egy oszlop")
print(C[:,0])
print("Submátrix")
print(D[1:3,2:6])

Egy elem
1
Egy sor
[1 2]
Egy oszlop
[1 3 5]
Submátrix
[[ 9 10 11 12]
 [16 17 18 19]]


Nullákból álló tömb létrehozása: [numpy.zeros()](https://docs.scipy.org/doc/numpy/reference/generated/numpy.zeros.html "adatlap").\
Feladat:
- hozzunk létre egy (1,5) teljesen zéró mátrixot!
- hozznk létre egy a C mátrix nagyságának megfelelő zéró mátrixot!

In [102]:
Z1 = np.zeros((1,5))
Z2 = np.zeros(C.shape)
print(Z1)
print(Z2)

[[0. 0. 0. 0. 0.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]


Hozzunk létre csupa egyesekből álló mátrixokat [numpy.ones()](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ones.html#numpy.ones "adatlap") segítségével.\
Feladat:
- hozzunk létre egy (1,5) tiszta egyes mátrixot!
- hozzunk létre egy a C mátrixnak megfelelő tiszta egyes mátrixot!
- hozzunk létre egy a C mátrix sorainak megfelelő "sorvektor"!

In [103]:
O1 = np.ones((1,5))
O2 = np.ones(C.shape)
O3 = np.ones(C.shape[0])
print(O1)
print(O2)
print(O3)

[[1. 1. 1. 1. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[1. 1. 1.]


Sokszor előfordulhat, hogy szükségünk van a mátrixunk egy adott más formára alakítására. Ezt a [numpy.reshape()](https://docs.scipy.org/doc/numpy/reference/generated/numpy.reshape.html "dokumentáció") segítségével tudjuk elérni.
Feladat:
- hozzunk létre egy sorvektort a D mátrixból!
- hozzunk létre a D mátrixból egy olyan mátrixot, ami a D mátrix dimenzióit cseréli meg! (NEM transzponáltját!)


In [ ]:
R1 = D.reshape(1,D.size)
R2 = D.reshape((7,4))

print(R1)
print(R2)

Mátrix transzponáltját a [numpy.ndarray.transpose()](https://docs.scipy.org/doc/numpy/reference/generated/numpy.transpose.html "dokumentáció") segítségével tudjuk létrehozni, vagy a $.T$ segítségéevel. Vigyáznunk kell itt, hogy a mátrix numpy mátrixként legyen értelmezve és ne numpy vektroként, azt ugyanis érintetlenül hagyja.\
Feladat:
- transzponáljuk az A,B,C,D mátrixokat!

In [ ]:
print('A:\n',A,'\nA.T:\n',A.T,'\n')
print('B:\n',B,'\nB.T\n',B.T,'\n')
print('C:\n',C,'\nC.T\n',C.T,'\n')
print('D:\n',D,'\nD.T\n',D.T,'\n')

Láthatjuk, hogy az A mátrixot nem transponáltuk. Ez azért van, mert az A mátrixunk egy NumPy vektor. Ezt legegyszerűbben úgy tudjuk ellenőrizni, ha a .shape paranccsal megnézzük. Ilyenkor az eredmény (x, ) alakú lesz a mátrixos (x, y) formátum helyett.

Néha szükségünk lehet arra, hogy egy mátrixot vektorként adjunk át egy függvénynek. Ilyenkor a [numpy.ndarray.flatten()](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.flatten.html "dokumentáció") -t használhatjuk.\
Feladat:
- "lapítsuk" a C és D mátrixokat!

In [ ]:
print('C lapítva:',C.flatten())
print('D lapítva:',D.flatten())

Ha egy mátrix elemeinek, sorainak, oszlopainak összegére vagyunk kíváncsiak, akkor a [numpy.sum()](https://docs.scipy.org/doc/numpy/reference/generated/numpy.sum.html "dokumentáció") használatos. Itt be tudjuk állítani hogy melyik tengely szerint szeretnénk összegezni.\
Feladat:
- összegezzük a D sorait majd külön az oszlopait majd az összes elemét!

In [ ]:
print(np.sum(D,axis=0))
print(np.sum(D,axis=1))
print(np.sum(D,axis=None))

Ha egy mátrix elemeinek, sorainak, oszlopainak átlagára vagyunk kíváncsiak, akkor a [numpy.mean()](https://docs.scipy.org/doc/numpy/reference/generated/numpy.mean.html#numpy.mean "dokumentáció") használatos. Itt be tudjuk állítani hogy melyik tengely szerint szeretnénk összegezni.\
Feladat:
- átlagoljuk a D sorait majd külön az oszlopait majd az összes elemét!

In [ ]:
print(np.mean(D,axis=0))
print(np.mean(D,axis=1))
print(np.mean(D,axis=None))

Ha egy mátrix elemeinek, sorainak, oszlopainak átlagára vagyunk kíváncsiak, akkor a [numpy.std()](https://docs.scipy.org/doc/numpy/reference/generated/numpy.mean.html#numpy.mean "dokumentáció") használatos. Itt be tudjuk állítani hogy melyik tengely szerint szeretnénk összegezni. Fontos még itt a ddof paraméter, melyet meg tudjuk határozni hogy milyen szórástípus szeretnénk (tapasztalati = 0 / korrigált tapasztalati = 1)

Feladat:

- számoljunk szórást a D sorait majd külön az oszlopait majd az összes elemét!
- próbáljuk ki mi történik ha a ddof paramétert 1 -re állítjuk!

In [ ]:
print(np.std(D,axis=0,ddof=1))
print(np.std(D,axis=1,ddof=1))
print(np.std(D,axis=None,ddof=0))
print(np.std(D,axis=None,ddof=1))

Szükségünk lehet a [numpy.log()](https://docs.scipy.org/doc/numpy/reference/generated/numpy.log.html "adatlap") függvényére is. Ez a NumPy tömbök elemein képes a természetes alapú logaritmus kiszámítására.

Feladat:
- Számoljuk ki az [1 2 3 4 5] vektor természetes alapú logaritmusát!

In [ ]:
a = np.array([1, 2, 3, 4, 5])
LOG = np.log(a)
print(LOG)

### MatPlotLib elemek:

MatPlotLib használata szintén nagyon hasonlatos a MATLAB -éhoz. Most a legegyszerűbb plot függvény használatát fogjuk átnézni. Először importáljuk be a csomagot, majd definiáljunk egy adathalmazt, amit szeretnénk kiíratni!

In [ ]:
import matplotlib.pyplot as plt
x = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
y = np.array([5, 6, 6, 7, 8, 3, 4, 4, 7, 10])

Rajzoltassuk ki az y(x) függvény értékeit. Ehhez a [matplotlib.pyplot.plot()](https://matplotlib.org/3.1.1/api/_as_gen/matplotlib.pyplot.plot.html "dokumentáció") -t használjuk!
Állítsuk be az tengelyeknek megfelelő tengelyfeliratot és adjunk címet is az ábrának. Ezeket rendre a [matplotlib.pyplot.xlabel()](https://matplotlib.org/3.1.1/api/_as_gen/matplotlib.pyplot.xlabel.html "dokumentáció") , [matplotlib.pyplot.ylabel()](https://matplotlib.org/3.1.1/api/_as_gen/matplotlib.pyplot.ylabel.html "dokumentáció") , [matplotlib.pyplot.title()](https://matplotlib.org/3.1.1/api/_as_gen/matplotlib.pyplot.title.html "dokumentáció") . Az eredményünket pedig a [matplotlib.pyplot.show()](https://matplotlib.org/3.1.1/api/_as_gen/matplotlib.pyplot.show.html "dokumentáció") segítségével jeleníthetjük meg.

In [ ]:
plt.plot(x,y)
plt.xlabel('x értékek')
plt.ylabel('y értékek')
plt.title('Ez egy ábra')
plt.show()

Tételezzük fel hogy szeretnénk kétféle értéket megjeleníteni az ábrán. Ezek elkülönítését szintén címkézéssel tehetjük meg, ami a plot parancson belül adható meg a label = '...' módon. Ha szeretnénk ezt megjeleníteni is az ábrán akkor a [matplotlib.pyplot.legend()](https://matplotlib.org/3.1.1/api/_as_gen/matplotlib.pyplot.legend.html "dokumentáció") segítségével tehetjük meg.\
Ennek bemutatására most definiáljunk egy yy változót és rajzoljuk szintén az ábrára!

In [ ]:
yy = np.array([ 0, 0, 0, 0, 1, 1, 2, 3, 4, 5])
plt.plot(x,y, label = 'y értékek')
plt.plot(x,yy, label = 'yy értékek')
plt.xlabel('x értékek')
plt.ylabel('y értékek')
plt.title('Ez egy ábra')
plt.legend()
plt.show()